name: kaloritakip
description: Basit kalori takip uygulamasÄ± - AI entegrasyonlu prototip
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  camera: ^0.10.0+5
  image_picker: ^0.8.7+4
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.0.7
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
